version: '1.0'
name: pipeline-20230511
displayName: pipeline-20230511
triggers:
  trigger: auto
  push:
    branches:
      prefix:
        - main
stages:
  - name: stage-2f7207cb
    displayName: 未命名
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: build@nodejs
        name: build_nodejs
        displayName: Nodejs 构建
        nodeVersion: 18.16.0
        commands:
          - '# 设置NPM源，提升安装速度'
          - npm install -g cnpm --registry=https://registry.npm.taobao.org
          - ''
          - '# 执行编译命令'
          - cnpm install && npm run build:prod
        artifacts:
          - name: BUILD_ARTIFACT
            path:
              - ./dist
        caches:
          - ~/.npm
          - ~/.yarn
        notify: []
        strategy:
          retry: '0'
